#!/bin/bash

# load configuration
source /etc/pakbak.conf

# abort when a var is empty
[[ ! "$target_folder" || ! "$keep_days" ]] && echo "configuration seems to be broken.. abort" && exit 1

# abort when target_folder isn't a folder
[[ ! -d "$target_folder" ]] && echo "$target_folder isn't a folder.. abort" && exit 2

# abort when keep_days contains something other than numbers or is <= 0
[[ ! "$keep_days" =~ ^[0-9]+$ || ! "$keep_days" > 0 ]] && echo "$keep_days isn't a valid number.. abort" && exit 3

# cleanup old files
find "$target_folder" -name 'pakbak-*.tar.xz' -type f -mtime +$keep_days -exec rm -v {} +

# make the backup
tar -cJf "$target_folder/pakbak-`date -Is`.tar.xz" "/var/lib/pacman/local"
