#!/bin/bash
# Copyright (C) 2013  Giuliano Schneider <gs93@gmx.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# load configuration
source /etc/pakbak.conf

# abort when a var is empty
[[ ! "$target_folder" || ! "$keep_days" ]] && echo "configuration seems to be broken.. abort" && exit 1

# abort when target_folder isn't a folder
[[ ! -d "$target_folder" ]] && echo "$target_folder isn't a folder.. abort" && exit 2

# abort when keep_days contains something other than numbers or is <= 0
[[ ! "$keep_days" =~ ^[0-9]+$ || ! "$keep_days" > 0 ]] && echo "$keep_days isn't a valid number.. abort" && exit 3

# cleanup old files
find "$target_folder" -name 'pakbak-*.tar.xz' -type f -mtime +$keep_days -exec rm -v {} +

# make the backup
tar -cJf "$target_folder/pakbak-`date -Is`.tar.xz" "/var/lib/pacman/local"
